### ISSUE TITLE
Error when computing predicted best parameters

### ISSUE THREAD

**Issue by ytterbium** [michaelhush/M-LOOP#120]
**Describe the bug**
When trying to compute the best predicted parameters and the associated cost

**To Reproduce**
Simply run the provided example `python_controlled_experiment.py`. At the end of the optimization, when trying to find the predicted optimum, there is a sklearn error, and the optimum is not computed. When adding noise to the cost function to force the predicted optimum to differ from the best found result, I still get the error. 

**Expected behavior**
I suppose I should get at this step the predicted best parameters

**Screenshots**
```
Process GaussianProcessLearner-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
     self.run()
  File "~/M-LOOP/mloop/learners.py", line 2048, in run
    self.find_global_minima()
  File "~/M-LOOP/mloop/learners.py", line 2095, in find_global_minima
    self.predicted_best_cost = self.cost_scaler.inverse_transform(self.predicted_best_scaled_cost)
  File "~/mloop/lib/python3.8/site-packages/scikit_learn-1.0-py3.8-linux-x86_64.egg/sklearn/preprocessing/_data.py", line 1016, in inverse_transform
    X = check_array(
  File "~/mloop/lib/python3.8/site-packages/scikit_learn-1.0-py3.8-linux-x86_64.egg/sklearn/utils/validation.py", line 761, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[-1.62357476].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

**Desktop (please complete the following information):**
- Ubuntu 20.04, with all the python packages installed via pip in a venv
- Arch Linux, with python dependencies from the package manager

**Comment by zakv** [comment]
Good digging! This is a super helpful bug report! I think you're right on the money.

The fix shouldn't be too hard, just reshaping some arrays while ensuring backwards compatibility. It's possible that I'll get a chance to resolve this in the next few days, but no guarantee. I have real-life bugs to deal with at the moment, so it depends on how that goes!

In the meantime are you ok working with scikit-learn 0.23.1? You also may want to use an editable M-LOOP installation with `pip install -e` to pull in the latest changes from Github after this bug is patched. I can give you more details on how to do that if desired, but it seems like you're pretty on top of things and likely already know how.

**Comment by ytterbium** [comment]
Well, I am not in a hurry. For now, I am just doing some tests and I still have to do the adaptation of our experiment to interface it to M-LOOP. And in any case, I could stick to scikit 0.23 for some time. 

I will probably have another question, but it will probably go into its own feature request.
