### ISSUE TITLE
Neural net learner fail

### ISSUE THREAD

**Issue by HiltonAshby** [michaelhush/M-LOOP#34]
Hi,
Using the new neural net learner we have experienced the following error at the end of a several hundred run long execution.

Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "c:\program files\anaconda3\lib\site-packages\mloop\learners.py", line 1914, in run
    self.fit_neural_net()
AttributeError: 'NeuralNetLearner' object has no attribute 'fit_neural_net'

The logs, archives, and config files are given in:

[mloop neural net fail.txt](https://github.com/michaelhush/M-LOOP/files/1577464/mloop.neural.net.fail.txt)
[mloopfiles.zip](https://github.com/michaelhush/M-LOOP/files/1577461/mloopfiles.zip)

Previously we have had good success using the gaussian process learner.

Thanks.

Ashby

**Comment by charmasaur** [comment]
Looks like the problem is in the predict_global_minima_at_end block, which
I never got around to supporting with the neural net. I'm overseas at the
moment but can look at a fix when I'm back.

Ashby, for a short term fix you can either set predict_global_minima_at_end
to false (I think this is a configuration option you can apply without
changing the code), or, if you installed from source, just comment out
lines 1913 and 1914 in learners.py.

Harry

On 21 Dec. 2017 1:35 pm, "HiltonAshby" <notifications@github.com> wrote:

Hi,
Using the new neural net learner we have experienced the following error at
the end of a several hundred run long execution.

Traceback (most recent call last):
File "c:\program files\anaconda3\lib\multiprocessing\process.py", line 249,
in _bootstrap
self.run()
File "c:\program files\anaconda3\lib\site-packages\mloop\learners.py", line
1914, in run
self.fit_neural_net()
AttributeError: 'NeuralNetLearner' object has no attribute 'fit_neural_net'

The logs, archives, and config files are given in:

mloop neural net fail.txt
<https://github.com/michaelhush/M-LOOP/files/1577464/mloop.neural.net.fail.txt>
mloopfiles.zip
<https://github.com/michaelhush/M-LOOP/files/1577461/mloopfiles.zip>

Previously we have had good success using the gaussian process learner.

Thanks.

Ashby

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/michaelhush/M-LOOP/issues/34>, or mute the thread
